# Generated by Django 6.1 on 2026-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="name",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
    ]
