# Generated by Django 6.1 on 2026-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_patientprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanrecord",
            name="diagnostic_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="symptomlog",
            name="questionnaire_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
