# Generated by Django 6.1 on 2026-09-03 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_scanrecord_diagnostic_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scanrecord",
            old_name="diagnostic_notes",
            new_name="notes",
        ),
    ]
