# Generated by Django 6.1 on 2026-09-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_rename_diagnostic_notes_scanrecord_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("raw_responses", models.JSONField()),
                ("model_output", models.JSONField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_submissions",
                        to="authentication.patientprofile",
                    ),
                ),
            ],
        ),
    ]
