# Generated by Django 6.1 on 2026-09-06 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_questionnairesubmission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scanrecord",
            old_name="notes",
            new_name="scan_note",
        ),
    ]
