# Generated by Django 6.1 on 2026-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Doctor's Name"),
                ),
                (
                    "location",
                    models.CharField(help_text="city location", max_length=255),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("gynecology", "Gynecologist"),
                            ("obstetrics", "Obstetrician"),
                            ("general", "General Practitioner"),
                            ("surgeon", "Surgical Specialist"),
                        ],
                        default="gynecology",
                        max_length=50,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal administrative notes only",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["name"],
            },
        ),
    ]
