# Generated by Django 6.1 on 2026-09-09 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_doctor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
