# Generated by Django 6.1 on 2026-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_delete_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
